# R/data.R

#' Example bulk RNAseq counts matrix
#'
#' A gene x sample counts matrix as generated by nf-core/rnaseq with star_rsem
#'
#' @format A data frame with 12 columns/samples and 78,317 rows/genes/features:
#'
#' @details
#' Used for demo purposes of '_targets_bulkRNA_DEseq2.R' demo pipeline for bulk RNAseq analysis. Generated using code in:
#' \code{data-raw/demo_counts.R}.
#'
#' @source Generated in \code{data-raw/demo_counts.R}.
#'
#' @examples
#' # Basic usage
#' head(demo_counts)
#' dim(demo_counts)
#'
#'
#' @keywords datasets
"demo_counts"


#' Example bulk RNAseq sample sheet
#'
#' An example sample sheet for 'demo_counts' with metadata mapping sample names to group information.
#'
#' @format A data frame with 12 rows/samples and 5 columns of metadata:
#'
#' @details
#' Used for demo purposes of '_targets_bulkRNA_DEseq2.R' demo pipeline for bulk RNAseq analysis. Generated using code in:
#' \code{data-raw/demo_samplesheet.R}.
#'
#' @source Generated in \code{data-raw/demo_samplesheet.R}.
#'
#' @examples
#' # Basic usage
#' head(demo_samplesheet)
#' dim(demo_samplesheet)
#'
#'
#' @keywords datasets
"demo_samplesheet"

#' Annotation table for mouse using ENSMBL GRCm38 from stephenturner/annotables package.
#'
#'
#' @format A data frame mouse annotation information.
#'
#' @details
#' Used for annotating datasets, swapping IDs between types etc.
#' \code{data-raw/grcm38.R}.
#'
#' @source Generated in \code{data-raw/grcm38.R}.
#'
#' @examples
#' # Basic usage
#' head(grcm38)
#' colnames(grcm38)
#'
#'
#'
#' @keywords internal
"grcm38"

#' Annotation table for human using ENSMBL GRCh38 from stephenturner/annotables package.
#'
#'
#' @format A data frame mouse annotation information.
#'
#' @details
#' Used for annotating datasets, swapping IDs between types etc.
#' \code{data-raw/grch38.R}.
#'
#' @source Generated in \code{data-raw/grch38.R}.
#'
#' @examples
#' # Basic usage
#' head(grch38)
#' colnames(grch38)
#'
#'
#'
#' @keywords internal
"grch38"
